services:
  db:
    image: postgres:15
    container_name: keisan_trading-db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: keisan_trading
    volumes:
      - keisan_trading_pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    container_name: keisan_trading-pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@keisantrading.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "8080:80"
    depends_on:
      - db

volumes:
  keisan_trading_pgdata: